### ISSUE TITLE
Undefined constant TAG_INVOICE_CALCULATOR

### ISSUE THREAD

**Issue by sawi-ws** [LiaraAlis/kimai2-SmallBusinessRuleBundle#10]
Hello,

i have this error in my Logfile.
Did i install anything wrong? Which data do you need?
Kimai is running in a Docker container.

![image](https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/assets/42534229/ecffadcb-5938-474a-beda-8c924e509b4e)

**Comment by maccanid** [comment]
I found the following workaround:
you have to change /plugins/SmallBusinessRuleBundle/DependencyInjection/Compiler/SmallBusinessDecoratorPass.php

add a private constant
```
class SmallBusinessDecoratorPass implements CompilerPassInterface
{
    private  const TAG_INVOICE_CALCULATOR = 'invoice.calculator';
```
and change  
`$taggedServices = $container->findTaggedServiceIds(Kernel::TAG_INVOICE_CALCULATOR);` 
to  
`$taggedServices = $container->findTaggedServiceIds(self::TAG_INVOICE_CALCULATOR);`

**Comment by LiaraAlis** [comment]
Thanks for reporting. I can confirm that this issue occurs starting with Kimai v2.7.0. I will provide a fix shortly.
