### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by danielegobbetti** [LiaraAlis/kimai2-SmallBusinessRuleBundle#6]
I noticed that this repository lacks a license and would like to know the license terms that apply to it.
If you are unsure about the license I would recommend choosing one from https://spdx.org/licenses/ , ideally both 
 "FSF Free/Libre" and "OSI Approved".

**Comment by LiaraAlis** [comment]
This extension is licensed under the MIT License as mentioned in `composer.json`:
https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/blob/81e50140e1eacd17ee0825214433d82c9de45544/composer.json#L10

But for sure, a license file should be added next time.

**Comment by danielegobbetti** [comment]
Nice, thanks for the clarification!
Would you mind if I try to add what's needed for compliance with the italian small business regulation to this plugin (it's similar/compatible with what you already did in the sense that VAT has to be removed but there are a few additional requirements)?

**Comment by LiaraAlis** [comment]
Feel free to make a issue and/or PR, but please explain what is needed for italian regulation to ensure I am able to understand the changes and classify if these changes are in conflict with regulations in Germany and we need to make it optional or similar.

**Comment by danielegobbetti** [comment]
Looking into the requirements I believe it would "pollute" your plugin too much, as the situation here is quite complicated and it makes little sense to expose users outside of Italy to this.
