### ISSUE TITLE
Not working with Kimai 2.0

### ISSUE THREAD

**Issue by TheR00st3r** [LiaraAlis/kimai2-SmallBusinessRuleBundle#7]
I used this plugin for some time.

Currently i get an error on startup

`NOTICE: PHP message: PHP Fatal error:  Uncaught Exception: Bundle "SmallBusinessRuleBundle" defines an invalid Kimai minimum version in extra.kimai.require. Please provide an integer as in Constants::VERSION_ID. in /opt/kimai/src/Plugin/PluginMetadata.php:59`

And the plugin is marked as NOT compatible in the plugin store: https://www.kimai.org/de/store/liaraalis-small-business-rule-bundle.html

Are there any plans to update this plugin?

**Comment by LiaraAlis** [comment]
Yes, I will update the plugin for Kimai 2. Unfortunately,  I'm still running kimai on v1, I had to update first. I hope I have time to do this in the next days.

**Comment by LiaraAlis** [comment]
I've updated the master branch with changes for Kimai v2. I rarely tested the changes but it seems to work correctly. If possible for you, I would happy if you could test the changes in master branch.

**Comment by TheR00st3r** [comment]
I have Installed the actual version. It worked fine. I will  give you feedback if I can notice any further problems.

**Comment by LiaraAlis** [comment]
New relase is out: https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/releases/tag/v2.0.0
