### ISSUE TITLE
Kimai2 crashing when opening settings

### ISSUE THREAD

**Issue by dzatoah** [LiaraAlis/kimai2-SmallBusinessRuleBundle#8]
`nano +222 /srv/sites/kimai/src/Controller/SystemConfigurationController.php` 

`2023-09-13 13:45:35] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Entity\Configuration::setName(): Argument #1 ($name) must be of type string, null given, called in /srv/sites/kimai/src/Repository/ConfigurationRepository.php on line 111" at /srv/sites/kimai/src/Entity/Configuration.php line 67 {"exception":"[object] (TypeError(code: 0): App\\Entity\\Configuration::setName(): Argument #1 ($name) must be of type string, null given, called in /srv/sites/kimai/src/Repository/ConfigurationRepository.php on line 111 at /srv/sites/kimai/src/Entity/Configuration.php:67)"} []`

A simple isset() check works, but it still can't load the lable for the small business rule setting and Kimai2 feels buggy. 

Kimai Doktor Version: 1.30.11 stable (prod)

**Comment by LiaraAlis** [comment]
The error does not look like it is caused by the small business rule plugin. Which Kimai version and which plugin version are you using?

**Comment by dzatoah** [comment]
I was using Kimai `1.30.11 stable`. I upgraded in the meantime to the latest Kimai version.
I think I used the latest git version of this plugin.
The issue was definitely fixed by removing the plugin.

**Comment by LiaraAlis** [comment]
Latest git version of the plugin represents plugin version `2.0` and only works with Kimai 2.0 and above. For Kimai `1.30.11` please use plugin in version `1.0.x`: https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/releases/tag/v1.0.2
